-- FINAL SQL Schema for CBSE TOPPERS
-- Copy and paste this into your Supabase SQL Editor

-- 1. Create the Students Table
-- student_id is a 10-character alphanumeric ID generated by the app
CREATE TABLE IF NOT EXISTS students (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT NOT NULL,
  dob DATE NOT NULL,
  class TEXT NOT NULL,
  stream TEXT,
  email TEXT UNIQUE NOT NULL,
  phone TEXT,
  password TEXT,
  student_id VARCHAR(10) UNIQUE NOT NULL
);

-- 2. Create the PE Results Table
CREATE TABLE IF NOT EXISTS pe_results (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  student_id TEXT NOT NULL,
  name TEXT NOT NULL,
  score INTEGER NOT NULL,
  paper_id TEXT NOT NULL,
  subject TEXT NOT NULL,
  answers JSONB DEFAULT '[]'::jsonb
);

-- 3. Security Configuration
-- Disabling RLS for initial development/demonstration
ALTER TABLE students DISABLE ROW LEVEL SECURITY;
ALTER TABLE pe_results DISABLE ROW LEVEL SECURITY;

-- Indexing for performance
CREATE INDEX IF NOT EXISTS idx_students_id_name ON students(student_id, name);
CREATE INDEX IF NOT EXISTS idx_results_student ON pe_results(student_id);
